./like_fourier 0 	dmo			so_Y1
./like_fourier 1	dmo			so_Y5
./like_fourier 0 	mb2 		so_Y1
./like_fourier 1	mb2			so_Y5
./like_fourier 0 	illustris 	so_Y1
./like_fourier 1	illustris 	so_Y5
./like_fourier 0 	eagle 		so_Y1
./like_fourier 1	eagle 		so_Y5
./like_fourier 0 	TNG100 		so_Y1
./like_fourier 1	TNG100 		so_Y5
./like_fourier 0 	HzAGN 		so_Y1
./like_fourier 1	HzAGN 		so_Y5
./like_fourier 0 	owls_AGN 	so_Y1
./like_fourier 1	owls_AGN 	so_Y5
